# Generated by Django 5.1.7 on 2025-04-11 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_balance_alter_user_car_plate_card'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Card',
        ),
    ]
